/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sijin' at '3/20/17 6:23 PM' with Gradle 2.9
 *
 * @author Sijin, @date 3/20/17 6:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
